package sk.riaver.protograph.proto.token;

public enum KeywordEnum {
	
	BOOL,BYTES,DOUBLE,ENUM,EXTEND,EXTENSIONS,
	FIXED32,FIXED64,FLOAT,GROUP,IMPORT,INF,INT32,INT64,MAP,MAX,MESSAGE,ONEOF,OPTION,
	OPTIONAL,PACKAGE,PUBLIC,REPEATED,REQUIRED,RESERVED,RETURNS,RPC,SERVICE,SFIXED32,
	SFIXED64,SINT32,SINT64,STREAM,STRING,SYNTAX,TO,UINT32,UINT64,WEAK

}
